"""Cluster raters that look like one actor. Two of three signals => same cluster.

Signals compared pairwise between rater profiles:
  1. same non-null funder address (case-insensitive)
  2. first-seen timestamps within `Config.sybil_window_s` seconds of each other
  3. Jaccard similarity of rated ratees >= `Config.sybil_jaccard`

Candidate pairs are generated by blocking (same funder, or sharing a ratee with
at most `Config.sybil_max_group` raters) so clustering is not O(n^2) over all raters.
Union-find makes the "at least 2 of 3 signals" relation transitive across a group.
"""
from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
from itertools import combinations
from typing import Optional

import pandas as pd

from .config import Config


@dataclass(frozen=True)
class RaterProfile:
    """A rater's identity fingerprint used for sybil clustering.

    first_seen_ts: earliest timestamp observed for this rater (seconds).
    funder: funding address, or None if unknown. Comparisons are case-insensitive.
    ratees: the set of ratee ids this rater has rated.
    """

    rater: str
    first_seen_ts: int
    funder: Optional[str]
    ratees: frozenset


class _UnionFind:
    """Union-find (disjoint set) over an arbitrary hashable universe of items."""

    def __init__(self, items):
        self.parent = {i: i for i in items}

    def find(self, x):
        while self.parent[x] != x:
            self.parent[x] = self.parent[self.parent[x]]
            x = self.parent[x]
        return x

    def union(self, a, b):
        ra, rb = self.find(a), self.find(b)
        if ra != rb:
            self.parent[max(ra, rb)] = min(ra, rb)


def _jaccard(a: frozenset, b: frozenset) -> float:
    if not a and not b:
        return 0.0
    return len(a & b) / len(a | b)


def _norm_funder(funder: Optional[str]) -> Optional[str]:
    return funder.lower() if funder is not None else None


def _signals(p: RaterProfile, q: RaterProfile, cfg: Config) -> int:
    """Count how many of the 3 sybil signals hold between two profiles (0-3)."""
    pf, qf = _norm_funder(p.funder), _norm_funder(q.funder)
    same_funder = pf is not None and pf == qf
    in_window = abs(p.first_seen_ts - q.first_seen_ts) <= cfg.sybil_window_s
    similar = _jaccard(p.ratees, q.ratees) >= cfg.sybil_jaccard
    return int(same_funder) + int(in_window) + int(similar)


def _candidate_pairs(profiles: list[RaterProfile], cfg: Config):
    """Yield candidate (rater, rater) pairs to test, via funder- and ratee-blocking.

    Each unordered pair is yielded at most once, even if it shares multiple
    blocking keys (e.g. same funder and multiple shared ratees).
    """
    by_funder: dict = defaultdict(list)
    by_ratee: dict = defaultdict(list)
    for p in profiles:
        if p.funder is not None:
            by_funder[_norm_funder(p.funder)].append(p.rater)
        for r in p.ratees:
            by_ratee[r].append(p.rater)
    groups = list(by_funder.values()) + [g for g in by_ratee.values() if len(g) <= cfg.sybil_max_group]
    seen = set()
    for group in groups:
        for a, b in combinations(sorted(set(group)), 2):
            if (a, b) not in seen:
                seen.add((a, b))
                yield a, b


def cluster_raters(profiles: list[RaterProfile], cfg: Config) -> dict[str, str]:
    """Cluster raters whose profiles share at least 2 of 3 sybil signals.

    Returns a dict mapping each rater to its cluster id, the lexicographically
    smallest rater name within that cluster. Raises ValueError if `profiles`
    contains duplicate rater names.
    """
    by_id: dict[str, RaterProfile] = {}
    for p in profiles:
        if p.rater in by_id:
            raise ValueError(f"duplicate rater in profiles: {p.rater!r}")
        by_id[p.rater] = p
    uf = _UnionFind(by_id.keys())
    for a, b in _candidate_pairs(profiles, cfg):
        if _signals(by_id[a], by_id[b], cfg) >= 2:
            uf.union(a, b)
    return {r: uf.find(r) for r in by_id}


def profiles_from_records(records: pd.DataFrame, meta: Optional[pd.DataFrame] = None) -> list[RaterProfile]:
    """Build one RaterProfile per rater from a validated record frame.

    first_seen_ts defaults to the minimum `ts` observed for that rater; funder
    defaults to None. When `meta` (columns: rater, first_seen_ts, funder) is
    given, its non-null values override the defaults for raters it covers;
    raters absent from `meta`, and rows in `meta` for raters absent from
    `records`, are ignored. funder is stored as given; comparisons in
    `cluster_raters` are case-insensitive.
    """
    g = records.groupby("rater")
    first = g["ts"].min()
    ratees = g["ratee"].agg(lambda s: frozenset(s))
    m = meta.set_index("rater") if meta is not None else None
    out = []
    for r in first.index:
        ts, funder = int(first[r]), None
        if m is not None and r in m.index:
            row = m.loc[r]
            if pd.notna(row["first_seen_ts"]):
                ts = int(row["first_seen_ts"])
            if pd.notna(row["funder"]):
                funder = str(row["funder"])
        out.append(RaterProfile(rater=r, first_seen_ts=ts, funder=funder, ratees=ratees[r]))
    return out
